-- AlterTable
ALTER TABLE "programmes_personnalises" ADD COLUMN     "accessibilite_handicap" TEXT,
ADD COLUMN     "cessation_anticipee" TEXT,
ADD COLUMN     "delai_acceptation" TEXT,
ADD COLUMN     "delai_acces" TEXT,
ADD COLUMN     "formateur" TEXT,
ADD COLUMN     "horaires" TEXT,
ADD COLUMN     "modalites_acces" TEXT,
ADD COLUMN     "modalites_evaluation" TEXT,
ADD COLUMN     "modalites_reglement" TEXT,
ADD COLUMN     "modalites_techniques" TEXT,
ADD COLUMN     "niveau_certification" TEXT,
ADD COLUMN     "prerequis" TEXT,
ADD COLUMN     "public_concerne" TEXT,
ADD COLUMN     "referent_pedagogique" TEXT,
ADD COLUMN     "referent_qualite" TEXT,
ADD COLUMN     "ressources_disposition" TEXT,
ADD COLUMN     "sanction_formation" TEXT,
ADD COLUMN     "tarif" TEXT;
